---

root: true

extends:
  - 'airbnb'
  - 'plugin:react/recommended'

env:
  browser: true
  node: true

rules:
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  react/jsx-props-no-spreading:
    - error
    - custom: ignore
  import/extensions: 0
