name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PRISMIC_API_TOKEN: ${{ secrets.PRISMIC_API_TOKEN }}
      PRISMIC_REPOSITORY_NAME: ${{ secrets.PRISMIC_REPOSITORY_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.5'
      - name: Install
        run: make install
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
