name: Release CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'
      - name: Install
        run: make install
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
      - name: Push to release
        run: git push -f origin main:release
      - name: Deploy
        run: curl -X POST -d {} ${{ secrets.DEPLOY_WEBHOOK_URL }}
